name: Check KVM & Virtualization

on:
  workflow_dispatch:

jobs:
  check-kvm:
    runs-on: ubuntu-latest
    steps:
      - name: Check CPU Virtualization Support
        run: |
          echo "=== CPU Flags ==="
          grep -E 'vmx|svm' /proc/cpuinfo || echo "No virtualization flags found"

      - name: Check if KVM module is loaded
        run: |
          echo "=== KVM Modules ==="
          lsmod | grep kvm || echo "KVM module not loaded"

      - name: Check KVM device
        run: |
          if [ -e /dev/kvm ]; then
            echo "/dev/kvm exists ✅"
          else
            echo "/dev/kvm not found ❌"
          fi

      - name: Check Virtualization Type
        run: systemd-detect-virt
