name: Ubuntu VM with SSH & ngrok

on:
  workflow_dispatch:

jobs:
  ubuntu-ngrok:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 openssh-server curl wget

      - name: Download Ubuntu Server ISO
        run: wget -q https://releases.ubuntu.com/22.04/ubuntu-22.04.5-live-server-amd64.iso -O ubuntu-server.iso

      - name: Create disk image
        run: qemu-img create -f qcow2 ubuntu-server.img 5G

      - name: Setup SSH server in runner (for GitHub runner itself)
        run: sudo service ssh start

      - name: Download and install ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt-get update && sudo apt-get install -y ngrok

      - name: Authenticate ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: ngrok config add-authtoken $NGROK_AUTH_TOKEN

      - name: Start QEMU VM with SSH port forwarding
        run: |
          nohup qemu-system-x86_64 \
            -enable-kvm \
            -m 2048 \
            -cpu host \
            -hda ubuntu-server.img \
            -cdrom ubuntu-server.iso \
            -boot d \
            -net user,hostfwd=tcp::2222-:22 \
            -net nic \
            -nographic \
            &

      - name: Start ngrok TCP tunnel to forward port 2222
        run: |
          nohup ngrok tcp 2222 --log=stdout > ngrok.log 2>&1 &
          sleep 10
          cat ngrok.log | grep -o 'tcp://[0-9\.]*:[0-9]*' | head -n1 > ngrok_url.txt
          echo "ngrok TCP URL:"
          cat ngrok_url.txt

      - name: Show ngrok URL
        run: cat ngrok_url.txt

      - name: Keep workflow running for 1 hour
        run: sleep 3600
